###Name: Aliyah Panjon Course: IT 202-004 Date: 2/11/2026 Assignment: IT-202 Phase 2 - CRUD Categories and Items Email: aep@njit.edu ###
POST http://localhost:3000/addbubbletea.test.php
Content-Type: application/x-www-form-urlencoded

bubbletea_id=16
&bubbletea_code=PEACHCF
&bubbletea_name=Peach Cheese Foam
&bubbletea_description=Sweet peach green tea with a refreshing fruity flavor, topped with creamy cheese foam for a perfect sweet and salty combination.
&bubbletea_size=Large
&bubbletea_brand=Gong-Cha
&bubbletea_size=Large
&bubbletea_sugar_level=50%
&bubbletea_ice_level=Less ice
&bubbletea_type_id=5
&bubbletea_buy_price=3.00
&bubbletea_sell_price=6.50
###
GET http://localhost:3000/listbubbletea.test.php
###
POST http://localhost:3000/changebubbletea.test.php
Content-Type: application/x-www-form-urlencoded

bubbletea_id=1
&bubbletea_code=MT
&bubbletea_name=Taro Milk Tea
&bubbletea_description=A creamy milk black tea blended with sweet taro tropical root vegetable flavor and chewy tapioca pearls.
&bubbletea_brand=Gong-Cha
&bubbletea_size=Large
&bubbletea_sugar_level=50%
&bubbletea_ice_level=Less ice
&bubbletea_type_id=1
&bubbletea_buy_price=2.80
&bubbletea_sell_price=6.75
###
POST http://localhost:3000/removebubbletea.test.php
Content-Type: application/x-www-form-urlencoded

bubbletea_id=5