###Name: Aliyah Panjon Course: IT 202-004 Date: 2/11/2026 Assignment: IT-202 Phase 2 - CRUD Categories and Items Email: aep@njit.edu ###
POST http://localhost:3000/addbubbletea.test.php
Content-Type: application/x-www-form-urlencoded

bubbletea_id=6
&bubbletea_code=MLK
&bubbletea_name=Coco Cream Milk
&bubbletea_description=Fresh choclate drink with crown sugar boba
&bubbletea_brand=Gong-Cha
&bubbletea_size=Small
&bubbletea_sugar_level=25%
&bubbletea_ice_level=Hot
&bubbletea_type_id=5
&bubbletea_buy_price=2.50
&bubbletea_sell_price=5.75
###
GET http://localhost:3000/listbubbletea.test.php
###
POST http://localhost:3000/changebubbletea.test.php
Content-Type: application/x-www-form-urlencoded

bubbletea_id=6
&bubbletea_code=MT
&bubbletea_name=Coco Cream Milk Tea
&bubbletea_description=Fresh chocolate milk tea drink with brown sugar boba
&bubbletea_brand=Gong-Cha
&bubbletea_size=Large
&bubbletea_sugar_level=50%
&bubbletea_ice_level=Less ice
&bubbletea_type_id=5
&bubbletea_buy_price=2.80
&bubbletea_sell_price=6.75
###
POST http://localhost:3000/removebubbletea.test.php
Content-Type: application/x-www-form-urlencoded

bubbletea_id=___